Section "Device"
    Identifier "GeminiFB"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
    Option "Rotate" "CCW"
EndSection

Section "InputClass"
    Identifier "Gemini touchscreen rotate CCW"
    MatchIsTouchscreen "on"
    Option "CalibrationMatrix" "1 0 0 0 1 0 0 0 1"
EndSection
